=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/aminoacids.dtd
<!-- entities -->

<!-- the top level element -->
<!ELEMENT amino-acid (name,abbreviation,symbol,molecular-formula,molecular-weight,isoelectric-point,CAS-registry-number)>

<!-- elements -->
<!ELEMENT name                      (#PCDATA)>
<!ELEMENT abbreviation              (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT molecular-formula         (#PCDATA)>
<!ELEMENT molecular-weight		(#PCDATA)>
<!ELEMENT isoelectric-point         (#PCDATA)>
<!ELEMENT CAS-registry-number		(#PCDATA)>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/methionine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Methionine</name>
   <abbreviation>met</abbreviation>
   <symbol>m</symbol>
   <molecular-formula>C5H11NO2S</molecular-formula>
   <molecular-weight>149.21</molecular-weight>
   <isoelectric-point>5.74</isoelectric-point>
   <CAS-registry-number>63-68-3</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/alanine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Alanine</name>
   <abbreviation>ala</abbreviation>
   <symbol>a</symbol>
   <molecular-formula>C3H7NO2</molecular-formula>
   <molecular-weight>89.09</molecular-weight>
   <isoelectric-point>6.00</isoelectric-point>
   <CAS-registry-number>56-41-7</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/proline.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Proline</name>
   <abbreviation>pro</abbreviation>
   <symbol>p</symbol>
   <molecular-formula>C5H9NO2</molecular-formula>
   <molecular-weight>115.13</molecular-weight>
   <isoelectric-point>6.30</isoelectric-point>
   <CAS-registry-number>147-85-3</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/glutamine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Glutamine</name>
   <abbreviation>gln</abbreviation>
   <symbol>q</symbol>
   <molecular-formula>C5H10N2O3</molecular-formula>
   <molecular-weight>146.15</molecular-weight>
   <isoelectric-point>5.65</isoelectric-point>
   <CAS-registry-number>56-85-9</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/glutamic-acid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Glutamic Acid</name>
   <abbreviation>glu</abbreviation>
   <symbol>e</symbol>
   <molecular-formula>C5H9NO4</molecular-formula>
   <molecular-weight>147.13</molecular-weight>
   <isoelectric-point>3.22</isoelectric-point>
   <CAS-registry-number>56-86-0</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/valine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Valine</name>
   <abbreviation>val</abbreviation>
   <symbol>v</symbol>
   <molecular-formula>C5H11NO2</molecular-formula>
   <molecular-weight>117.15</molecular-weight>
   <isoelectric-point>5.96</isoelectric-point>
   <CAS-registry-number>72-18-4</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/glycine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Glycine</name>
   <abbreviation>gly</abbreviation>
   <symbol>g</symbol>
   <molecular-formula>C2H5NO2</molecular-formula>
   <molecular-weight>75.07</molecular-weight>
   <isoelectric-point>5.97</isoelectric-point>
   <CAS-registry-number>56-40-6</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/arginine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Arginine</name>
   <abbreviation>arg</abbreviation>
   <symbol>r</symbol>
   <molecular-formula>C6H14N4O2</molecular-formula>
   <molecular-weight>174.20</molecular-weight>
   <isoelectric-point>11.15</isoelectric-point>
   <CAS-registry-number>74-79-3</CAS-registry-number>
</amino-acid>
