=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/aminoacids.dtd
<!-- entities -->

<!-- the top level element -->
<!ELEMENT amino-acid (name,abbreviation,symbol,molecular-formula,molecular-weight,isoelectric-point,CAS-registry-number)>

<!-- elements -->
<!ELEMENT name                      (#PCDATA)>
<!ELEMENT abbreviation              (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT molecular-formula         (#PCDATA)>
<!ELEMENT molecular-weight		(#PCDATA)>
<!ELEMENT isoelectric-point         (#PCDATA)>
<!ELEMENT CAS-registry-number		(#PCDATA)>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/phenylalanine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Phenylalanine</name>
   <abbreviation>phe</abbreviation>
   <symbol>f</symbol>
   <molecular-formula>C9H11NO2</molecular-formula>
   <molecular-weight>165.19</molecular-weight>
   <isoelectric-point>5.48</isoelectric-point>
   <CAS-registry-number>63-91-2</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/asparagine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Asparagine</name>
   <abbreviation>asn</abbreviation>
   <symbol>n</symbol>
   <molecular-formula>C4H8N2O3</molecular-formula>
   <molecular-weight>132.12</molecular-weight>
   <isoelectric-point>5.41</isoelectric-point>
   <CAS-registry-number>5794-13-8</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/isoleucine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Isoleucine</name>
   <abbreviation>ile</abbreviation>
   <symbol>i</symbol>
   <molecular-formula>C6H13NO2</molecular-formula>
   <molecular-weight>131.17</molecular-weight>
   <isoelectric-point>5.94</isoelectric-point>
   <CAS-registry-number>73-32-5</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/leucine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Leucine</name>
   <abbreviation>leu</abbreviation>
   <symbol>l</symbol>
   <molecular-formula>C6H13NO2</molecular-formula>
   <molecular-weight>131.17</molecular-weight>
   <isoelectric-point>5.98</isoelectric-point>
   <CAS-registry-number>61-90-5</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/aspartic-acid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Aspartic Acid</name>
   <abbreviation>asp</abbreviation>
   <symbol>d</symbol>
   <molecular-formula>C4H7NO4</molecular-formula>
   <molecular-weight>133.10</molecular-weight>
   <isoelectric-point>2.77</isoelectric-point>
   <CAS-registry-number>56-84-8</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/tyrosine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Tyrosine</name>
   <abbreviation>tyr</abbreviation>
   <symbol>y</symbol>
   <molecular-formula>C9H11NO3</molecular-formula>
   <molecular-weight>181.19</molecular-weight>
   <isoelectric-point>5.66</isoelectric-point>
   <CAS-registry-number>60-18-4</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/cysteine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Cysteine</name>
   <abbreviation>cys</abbreviation>
   <symbol>c</symbol>
   <molecular-formula>C3H7NO2S</molecular-formula>
   <molecular-weight>121.15</molecular-weight>
   <isoelectric-point>5.02</isoelectric-point>
   <CAS-registry-number>52-90-4</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/lysine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Lysine</name>
   <abbreviation>lys</abbreviation>
   <symbol>k</symbol>
   <molecular-formula>C6H14N2O2</molecular-formula>
   <molecular-weight>146.19</molecular-weight>
   <isoelectric-point>9.59</isoelectric-point>
   <CAS-registry-number>39665-12-8</CAS-registry-number>
</amino-acid>
