=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/aminoacids.dtd
<!-- entities -->

<!-- the top level element -->
<!ELEMENT amino-acid (name,abbreviation,symbol,molecular-formula,molecular-weight,isoelectric-point,CAS-registry-number)>

<!-- elements -->
<!ELEMENT name                      (#PCDATA)>
<!ELEMENT abbreviation              (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT molecular-formula         (#PCDATA)>
<!ELEMENT molecular-weight		(#PCDATA)>
<!ELEMENT isoelectric-point         (#PCDATA)>
<!ELEMENT CAS-registry-number		(#PCDATA)>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/tryptophan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Tryptophan</name>
   <abbreviation>trp</abbreviation>
   <symbol>w</symbol>
   <molecular-formula>C11H12N2O2</molecular-formula>
   <molecular-weight>204.23</molecular-weight>
   <isoelectric-point>5.89</isoelectric-point>
   <CAS-registry-number>73-22-3</CAS-registry-number>
</amino-acid>

=== pulquero/jsci/jsci/classes/JSci/biology/aminoacids/serine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amino-acid SYSTEM "aminoacids.dtd">
<amino-acid>
   <name>Serine</name>
   <abbreviation>ser</abbreviation>
   <symbol>s</symbol>
   <molecular-formula>C3H7NO3</molecular-formula>
   <molecular-weight>105.09</molecular-weight>
   <isoelectric-point>5.68</isoelectric-point>
   <CAS-registry-number>56-45-1</CAS-registry-number>
</amino-acid>
