=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/elements.dtd
<!-- entities -->

<!ENTITY % series-values "alkali-metal|alkali-earth-metal|halogen|noble-gas|non-metal|metal|rare-earth-metal|transition-metal">
<!ENTITY % properties "electronegativity,ionization-potentials,covalent-radius,atomic-radius,melting-point,boiling-point,density,specific-heat,electrical-conductivity,thermal-conductivity">
<!ENTITY % potentials "first,second?,third?,fourth?">

<!-- the top level element -->

<!ELEMENT element (name,symbol,atomic-number,mass-number,%properties;,isotopes?)>
<!ATTLIST element series (%series-values;) #REQUIRED>

<!-- elements -->

<!ELEMENT name                      (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT atomic-number             (#PCDATA)>
<!ELEMENT mass-number               (#PCDATA)>
<!ELEMENT electronegativity         (#PCDATA)>
<!ELEMENT ionization-potentials     (%potentials;)>
   <!ELEMENT first    (#PCDATA)>
   <!ELEMENT second   (#PCDATA)>
   <!ELEMENT third    (#PCDATA)>
   <!ELEMENT fourth   (#PCDATA)>
<!ELEMENT covalent-radius           (#PCDATA)>
<!ELEMENT atomic-radius             (#PCDATA)>
<!ELEMENT melting-point             (#PCDATA)>
<!ELEMENT boiling-point             (#PCDATA)>
<!ELEMENT density                   (#PCDATA)>
<!ELEMENT specific-heat             (#PCDATA)>
<!ELEMENT electrical-conductivity   (#PCDATA)>
<!ELEMENT thermal-conductivity      (#PCDATA)>
<!ELEMENT isotopes                  (isotope,isotope+)>
<!ELEMENT isotope                   (mass-number,abundance)>
<!ELEMENT abundance                 (#PCDATA)>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/tungsten.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="transition-metal">
   <name>Tungsten</name>
   <symbol>W</symbol>
   <atomic-number>74</atomic-number>
   <mass-number>184</mass-number>
   <electronegativity>2.36</electronegativity>
   <covalent-radius>1.30</covalent-radius>
   <atomic-radius>2.02</atomic-radius>
   <melting-point>3680.0</melting-point>
   <boiling-point>5828.0</boiling-point>
   <density>19.3</density>
   <specific-heat>0.13</specific-heat>
   <electrical-conductivity>0.189e6</electrical-conductivity>
   <thermal-conductivity>1.74</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/tellurium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="non-metal">
   <name>Tellurium</name>
   <symbol>Te</symbol>
   <atomic-number>52</atomic-number>
   <mass-number>128</mass-number>
   <electronegativity>2.1</electronegativity>
   <covalent-radius>1.37</covalent-radius>
   <atomic-radius>1.42</atomic-radius>
   <melting-point>722.65</melting-point>
   <boiling-point>1621.0</boiling-point>
   <density>6.24</density>
   <specific-heat>0.20</specific-heat>
   <electrical-conductivity>2.0</electrical-conductivity>
   <thermal-conductivity>0.0235</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/curium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="rare-earth-metal">
   <name>Curium</name>
   <symbol>Cm</symbol>
   <atomic-number>96</atomic-number>
   <mass-number>247</mass-number>
   <electronegativity>1.3</electronegativity>
   <melting-point>1340</melting-point>
   <density>13.51</density>
   <thermal-conductivity>0.1</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/iodine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="halogen">
   <name>Iodine</name>
   <symbol>I</symbol>
   <atomic-number>53</atomic-number>
   <mass-number>127</mass-number>
   <electronegativity>2.66</electronegativity>
   <covalent-radius>1.333</covalent-radius>
   <atomic-radius>1.32</atomic-radius>
   <melting-point>386.7</melting-point>
   <boiling-point>458.4</boiling-point>
   <density>4.93</density>
   <specific-heat>0.214</specific-heat>
   <electrical-conductivity>8.0e-10</electrical-conductivity>
   <thermal-conductivity>0.00449</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/nitrogen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="non-metal">
   <name>Nitrogen</name>
   <symbol>N</symbol>
   <atomic-number>7</atomic-number>
   <mass-number>14</mass-number>
   <electronegativity>3.04</electronegativity>
   <covalent-radius>0.70</covalent-radius>
   <atomic-radius>0.75</atomic-radius>
   <melting-point>63.14</melting-point>
   <boiling-point>77.35</boiling-point>
   <density>0.0012506</density>
   <specific-heat>1.04</specific-heat>
   <thermal-conductivity>0.0002598</thermal-conductivity>
   <isotopes>
      <isotope><mass-number>14</mass-number><abundance>99.63</abundance></isotope>
      <isotope><mass-number>15</mass-number><abundance>0.37</abundance></isotope>
   </isotopes>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/promethium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="rare-earth-metal">
   <name>Promethium</name>
   <symbol>Pm</symbol>
   <atomic-number>61</atomic-number>
   <mass-number>145</mass-number>
   <electronegativity>1.13</electronegativity>
   <covalent-radius>1.63</covalent-radius>
   <atomic-radius>2.62</atomic-radius>
   <melting-point>1204.0</melting-point>
   <boiling-point>3785.0</boiling-point>
   <density>6.475</density>
   <specific-heat>0.18</specific-heat>
   <thermal-conductivity>0.179</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/chlorine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="halogen">
   <name>Chlorine</name>
   <symbol>Cl</symbol>
   <atomic-number>17</atomic-number>
   <mass-number>35</mass-number>
   <electronegativity>3.16</electronegativity>
   <covalent-radius>0.99</covalent-radius>
   <atomic-radius>0.97</atomic-radius>
   <melting-point>172.16</melting-point>
   <boiling-point>239.1</boiling-point>
   <density>0.003214</density>
   <specific-heat>0.48</specific-heat>
   <electrical-conductivity>0.0</electrical-conductivity>
   <thermal-conductivity>0.089e-3</thermal-conductivity>
   <isotopes>
      <isotope><mass-number>35</mass-number><abundance>75.78</abundance></isotope>
      <isotope><mass-number>37</mass-number><abundance>24.22</abundance></isotope>
   </isotopes>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/lead.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="metal">
   <name>Lead</name>
   <symbol>Pb</symbol>
   <atomic-number>82</atomic-number>
   <mass-number>207</mass-number>
   <electronegativity>2.33</electronegativity>
   <covalent-radius>1.54</covalent-radius>
   <atomic-radius>1.81</atomic-radius>
   <melting-point>600.6</melting-point>
   <boiling-point>2023.0</boiling-point>
   <density>11.34</density>
   <specific-heat>0.13</specific-heat>
   <electrical-conductivity>0.0481e6</electrical-conductivity>
   <thermal-conductivity>0.353</thermal-conductivity>
   <isotopes>
      <isotope><mass-number>204</mass-number><abundance>1.4</abundance></isotope>
      <isotope><mass-number>206</mass-number><abundance>24.1</abundance></isotope>
      <isotope><mass-number>207</mass-number><abundance>22.1</abundance></isotope>
      <isotope><mass-number>208</mass-number><abundance>52.4</abundance></isotope>
   </isotopes>
</element>
