=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/elements.dtd
<!-- entities -->

<!ENTITY % series-values "alkali-metal|alkali-earth-metal|halogen|noble-gas|non-metal|metal|rare-earth-metal|transition-metal">
<!ENTITY % properties "electronegativity,ionization-potentials,covalent-radius,atomic-radius,melting-point,boiling-point,density,specific-heat,electrical-conductivity,thermal-conductivity">
<!ENTITY % potentials "first,second?,third?,fourth?">

<!-- the top level element -->

<!ELEMENT element (name,symbol,atomic-number,mass-number,%properties;,isotopes?)>
<!ATTLIST element series (%series-values;) #REQUIRED>

<!-- elements -->

<!ELEMENT name                      (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT atomic-number             (#PCDATA)>
<!ELEMENT mass-number               (#PCDATA)>
<!ELEMENT electronegativity         (#PCDATA)>
<!ELEMENT ionization-potentials     (%potentials;)>
   <!ELEMENT first    (#PCDATA)>
   <!ELEMENT second   (#PCDATA)>
   <!ELEMENT third    (#PCDATA)>
   <!ELEMENT fourth   (#PCDATA)>
<!ELEMENT covalent-radius           (#PCDATA)>
<!ELEMENT atomic-radius             (#PCDATA)>
<!ELEMENT melting-point             (#PCDATA)>
<!ELEMENT boiling-point             (#PCDATA)>
<!ELEMENT density                   (#PCDATA)>
<!ELEMENT specific-heat             (#PCDATA)>
<!ELEMENT electrical-conductivity   (#PCDATA)>
<!ELEMENT thermal-conductivity      (#PCDATA)>
<!ELEMENT isotopes                  (isotope,isotope+)>
<!ELEMENT isotope                   (mass-number,abundance)>
<!ELEMENT abundance                 (#PCDATA)>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/helium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="noble-gas">
   <name>Helium</name>
   <symbol>He</symbol>
   <atomic-number>2</atomic-number>
   <mass-number>4</mass-number>
   <electronegativity>0.0</electronegativity>
   <ionization-potentials>
      <first>24.587</first>
      <second>54.416</second>
   </ionization-potentials>
   <covalent-radius>0.93</covalent-radius>
   <atomic-radius>0.49</atomic-radius>
   <melting-point>0.95</melting-point>
   <boiling-point>4.215</boiling-point>
   <density>0.0001787</density>
   <specific-heat>5.193</specific-heat>
   <electrical-conductivity>0.0</electrical-conductivity>
   <thermal-conductivity>0.00152</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/arsenic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="non-metal">
   <name>Arsenic</name>
   <symbol>As</symbol>
   <atomic-number>33</atomic-number>
   <mass-number>75</mass-number>
   <electronegativity>2.18</electronegativity>
   <covalent-radius>1.21</covalent-radius>
   <atomic-radius>1.33</atomic-radius>
   <melting-point>1081</melting-point>
   <boiling-point>876</boiling-point>
   <density>5.72</density>
   <specific-heat>0.33</specific-heat>
   <electrical-conductivity>0.0345e6</electrical-conductivity>
   <thermal-conductivity>0.5</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/hydrogen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="non-metal">
   <name>Hydrogen</name>
   <symbol>H</symbol>
   <atomic-number>1</atomic-number>
   <mass-number>1</mass-number>
   <electronegativity>2.20</electronegativity>
   <ionization-potentials>
      <first>13.598</first>
   </ionization-potentials>
   <covalent-radius>0.371</covalent-radius>
   <atomic-radius>0.79</atomic-radius>
   <melting-point>14.025</melting-point>
   <boiling-point>20.268</boiling-point>
   <density>0.0000899</density>
   <specific-heat>14.304</specific-heat>
   <electrical-conductivity>0.0</electrical-conductivity>
   <thermal-conductivity>0.001815</thermal-conductivity>
   <isotopes>
      <isotope><mass-number>1</mass-number><abundance>99.985</abundance></isotope>
      <isotope><mass-number>2</mass-number><abundance>0.015</abundance></isotope>
   </isotopes>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/americium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="rare-earth-metal">
   <name>Americium</name>
   <symbol>Am</symbol>
   <atomic-number>95</atomic-number>
   <mass-number>243</mass-number>
   <electronegativity>1.3</electronegativity>
   <melting-point>1268.0</melting-point>
   <boiling-point>2880.0</boiling-point>
   <density>13.6</density>
   <specific-heat>0.11</specific-heat>
   <electrical-conductivity>0.022e6</electrical-conductivity>
   <thermal-conductivity>0.1</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/xenon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="noble-gas">
   <name>Xenon</name>
   <symbol>Xe</symbol>
   <atomic-number>54</atomic-number>
   <mass-number>131</mass-number>
   <electronegativity>0.0</electronegativity>
   <covalent-radius>1.31</covalent-radius>
   <atomic-radius>1.24</atomic-radius>
   <melting-point>161.36</melting-point>
   <boiling-point>165.03</boiling-point>
   <density>0.00588</density>
   <specific-heat>0.158</specific-heat>
   <electrical-conductivity>0.0</electrical-conductivity>
   <thermal-conductivity>0.0569e-3</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/neptunium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="rare-earth-metal">
   <name>Neptunium</name>
   <symbol>Np</symbol>
   <atomic-number>93</atomic-number>
   <mass-number>237</mass-number>
   <electronegativity>1.36</electronegativity>
   <melting-point>910.0</melting-point>
   <density>20.45</density>
   <electrical-conductivity>0.00822e6</electrical-conductivity>
   <thermal-conductivity>0.063</thermal-conductivity>
</element>

=== pulquero/jsci/jsci/classes/JSci/chemistry/periodictable/protactinium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="rare-earth-metal">
   <name>Protactinium</name>
   <symbol>Pa</symbol>
   <atomic-number>91</atomic-number>
   <mass-number>231</mass-number>
   <electronegativity>1.5</electronegativity>
   <density>15.4</density>
   <specific-heat>0.12</specific-heat>
   <electrical-conductivity>0.0529e6</electrical-conductivity>
   <thermal-conductivity>0.47</thermal-conductivity>
</element>
